/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Radar */
        get: operations["get_radar_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scope/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Scope */
        get: operations["check_scope_scope_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Board */
        get: operations["get_board_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ask Project */
        get: operations["ask_project_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Github Webhook */
        post: operations["github_webhook_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoardCard */
        BoardCard: {
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "backlog" | "todo" | "in_progress" | "in_review" | "done";
            /** Assignee */
            assignee: string | null;
            /** Ref */
            ref: string | null;
        };
        /** BoardResponse */
        BoardResponse: {
            /** Cards */
            cards: components["schemas"]["BoardCard"][];
        };
        /** Detection */
        Detection: {
            /** Id */
            id: string;
            /**
             * Kind
             * @default conflict
             * @constant
             */
            kind: "conflict";
            /** Actors */
            actors: string[];
            /** Branches */
            branches: string[];
            /** Files */
            files: string[];
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "med" | "high";
            /** Confidence */
            confidence: number;
            /** Rationale */
            rationale: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Error */
            error: string;
            /** Message */
            message: string;
            /** Status */
            status: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Mode
             * @enum {string}
             */
            mode: "local" | "hosted";
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: string[];
        };
        /** RadarResponse */
        RadarResponse: {
            /** Detections */
            detections: components["schemas"]["Detection"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScopeVerdict */
        ScopeVerdict: {
            /** Ref */
            ref: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "in_scope" | "drift" | "non_goal_violation";
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_radar_radar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarResponse"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    check_scope_scope_check_get: {
        parameters: {
            query: {
                ref: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeVerdict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_board_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ask_project_query_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    github_webhook_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-hub-signature-256"?: string | null;
                "x-github-event"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Geçersiz webhook imzası */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
