/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Radar */
        get: operations["get_radar_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scope/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Scope */
        get: operations["check_scope_scope_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Board */
        get: operations["get_board_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ask Project */
        get: operations["ask_project_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoardCard */
        BoardCard: {
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "backlog" | "todo" | "in_progress" | "in_review" | "done";
            /** Assignee */
            assignee: string | null;
            /** Ref */
            ref: string | null;
        };
        /** BoardResponse */
        BoardResponse: {
            /** Cards */
            cards: components["schemas"]["BoardCard"][];
        };
        /** Detection */
        Detection: {
            /** Id */
            id: string;
            /**
             * Kind
             * @default conflict
             * @constant
             */
            kind: "conflict";
            /** Actors */
            actors: string[];
            /** Branches */
            branches: string[];
            /** Files */
            files: string[];
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "med" | "high";
            /** Confidence */
            confidence: number;
            /** Rationale */
            rationale: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Error */
            error: string;
            /** Message */
            message: string;
            /** Status */
            status: number;
        };
        /**
         * GraphEdge
         * @description Aktör -> modül kenarı (#104). module = path'in ilk 2 segmenti (HESAPLANIR).
         */
        GraphEdge: {
            /** Actor */
            actor: string;
            /** Module */
            module: string;
            /** Count */
            count: number;
            /**
             * Last Ts
             * Format: date-time
             */
            last_ts: string;
            /** Is Active Declared */
            is_active_declared: boolean;
        };
        /**
         * GraphNode
         * @description GET /graph düğümü (#104) — kontrat: docs/sprint2-kontratlar.md Ek A.
         */
        GraphNode: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "actor" | "module";
            /** Weight */
            weight: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Mode
             * @enum {string}
             */
            mode: "local" | "hosted";
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: string[];
        };
        /** RadarResponse */
        RadarResponse: {
            /** Detections */
            detections: components["schemas"]["Detection"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScopeItemRef */
        ScopeItemRef: {
            /** Quote */
            quote: string;
            /** Item Id */
            item_id?: string | null;
            /** Section */
            section?: ("goal" | "in_scope" | "non_goals") | null;
            /** Line */
            line?: number | null;
        };
        /** ScopeVerdict */
        ScopeVerdict: {
            /** Ref */
            ref: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "in_scope" | "drift" | "non_goal_violation";
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: string | components["schemas"]["ScopeItemRef"];
            /**
             * Match None
             * @default false
             */
            match_none: boolean;
            /** Judged At */
            judged_at?: string | null;
            signals?: components["schemas"]["Signals"] | null;
        };
        /** Signals */
        Signals: {
            /** Files */
            files: string[];
            /** Matched Text */
            matched_text?: string | null;
        };
        /**
         * TouchGraph
         * @description GET /graph çıktısı (#104) — sıfır LLM, saf NormalizedEvent + active/ aggregation.
         */
        TouchGraph: {
            /** Window Days */
            window_days: number;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_radar_radar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarResponse"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    check_scope_scope_check_get: {
        parameters: {
            query: {
                ref: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeVerdict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_board_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ask_project_query_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_graph_graph_get: {
        parameters: {
            query?: {
                window_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TouchGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Kalici saglayici hatasi (GitHub/Gemini) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gecici olarak erisilemez */
            503: {
                headers: {
                    /** @description Saniye — yalniz kendiliginden duzelebilir durumlarda */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
