"""judge verdicts

Kalıcı judge yargı önbelleği (#259, GÖREV 1/2): `judge_verdicts` tablosu —
`CachedConflictJudge` (bellek, TTL'li) MISS verince `PersistentJudge`'ın
baktığı ikinci katman. `cache_key` `engine/cache.py::_digest` ile üretilen
içerik-adresli anahtardır (model dahil, çağıranın sorumluluğu); `model`
kolonu ayrıca bayatlık teşhisi için düz metin olarak tutulur. Bkz.
ensemble.store.models.JudgeVerdictRow.

Revision ID: 3e1e00e45b4c
Revises: d1a7c3e90f42
Create Date: 2026-07-27 10:00:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e1e00e45b4c"
# #263 (task_status_events, d1a7c3e90f42) main'e ONCE indi; bu migration
# onun USTUNE zincirlenir. Ikisi de c4f1d6a2b8e9'a baglanirsa alembic IKI
# head gorur ve `upgrade head` belirsiz kalir.
down_revision: Union[str, None] = "d1a7c3e90f42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "judge_verdicts",
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("detection", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    op.create_index(op.f("ix_judge_verdicts_model"), "judge_verdicts", ["model"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_judge_verdicts_model"), table_name="judge_verdicts")
    op.drop_table("judge_verdicts")
    # ### end Alembic commands ###
