"""Alembic migration script template for ensemble store.

initial tables

Revision ID: b636480eb1c7
Revises: 
Create Date: 2026-07-11 11:57:19.931491
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b636480eb1c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_actor'), 'events', ['actor'], unique=False)
    op.create_index(op.f('ix_events_ts'), 'events', ['ts'], unique=False)
    op.create_table('presence',
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=True),
    sa.Column('module', sa.String(length=255), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('since', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('handle')
    )
    op.create_table('task_projection',
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_projection_status'), 'task_projection', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_projection_status'), table_name='task_projection')
    op.drop_table('task_projection')
    op.drop_table('presence')
    op.drop_index(op.f('ix_events_ts'), table_name='events')
    op.drop_index(op.f('ix_events_actor'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
