"""task status events

Kalıcı durum günlüğü (D-55, İş 2): `task_status_events` append-only tablosu +
`task_projection`'a `seed_status` / `last_transition_at` / `last_event_id`
kolonları. `task_projection.status` artık `fold_status(seed, events)`
sonucudur — bkz. ensemble.store.rebuild.

Revision ID: d1a7c3e90f42
Revises: c4f1d6a2b8e9
Create Date: 2026-07-27 09:00:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1a7c3e90f42"
down_revision: Union[str, None] = "c4f1d6a2b8e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_status_events",
        sa.Column("source_event_id", sa.String(length=255), nullable=False),
        sa.Column("task_id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("resets", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.PrimaryKeyConstraint("source_event_id", "task_id"),
    )
    op.create_index(
        op.f("ix_task_status_events_task_id"), "task_status_events", ["task_id"], unique=False
    )
    op.create_index(op.f("ix_task_status_events_ts"), "task_status_events", ["ts"], unique=False)

    # batch_alter_table: SQLite'ta tablo-yeniden-oluşturma ile, Postgres'te
    # düz ALTER TABLE ile — tek kod yolu iki dialekte de çalışır.
    with op.batch_alter_table("task_projection") as batch_op:
        batch_op.add_column(
            sa.Column(
                "seed_status",
                sa.String(length=20),
                nullable=False,
                server_default=sa.text("'backlog'"),
            )
        )
        batch_op.add_column(sa.Column("last_transition_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("last_event_id", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_projection") as batch_op:
        batch_op.drop_column("last_event_id")
        batch_op.drop_column("last_transition_at")
        batch_op.drop_column("seed_status")

    op.drop_index(op.f("ix_task_status_events_ts"), table_name="task_status_events")
    op.drop_index(op.f("ix_task_status_events_task_id"), table_name="task_status_events")
    op.drop_table("task_status_events")
    # ### end Alembic commands ###
